DUOS-1198[risk=no] DAR Cancel Not Allowed if Open/Approved/Denied elections exist
broadinstitute/consent pull request #1049
Opened 2021-04-28 17:31 UTC by JVThomas

Addresses [DUOS-1198](https://broadworkbench.atlassian.net/browse/DUOS-1198)

PR prevents researchers from canceling a submitted DAR if an election has been created for that DAR. New criteria is checked for in ```DataAccessRequestService.cancelDataAccessRequest```. Tests have also been updated to account for this new condition. 

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-04-28 20:51 UTC, rushtong requested changes
See comments inline. Good work, but there is some additional cleanup that can be done.

2021-04-28 20:51 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessRequestResource.java
> -            List<User> usersToNotify = dataAccessRequestService.getUserEmailAndCancelElection(referenceId);
This method is no longer used by any application code, just in tests. We can remove it from the service class. There are likely other unused methods as a result of removing this functionality.

2021-04-28 20:51 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessRequestResource.java
> -                emailNotifierService.sendCancelDARRequestMessage(usersToNotify, dar.getData().getDarCode());
This method is no longer in use, we can remove it from the email service.

2021-04-28 20:51 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/DataAccessRequestService.java
> +            throw new IllegalArgumentException("Cancelling this DAR is not allowed");
I think `UnsupportedOperationException` is more appropriate here. The reference id is technically a valid argument, but we are choosing not to perform the requested operation due to business policy. You could even make an argument that this is a 409 conflict exception, but I think that's a bit of a stretch.

2021-04-29 14:29 UTC, raejohanek approved these changes
Code looks good! nice clean up!

2021-04-29 15:26 UTC, rushtong approved these changes
One minor comment inline, then 👍🏽

2021-04-29 15:26 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/DataAccessRequestService.java
> +            //Is this the right exception to use?
nit, outdated comment

2021-04-30 13:36 UTC, merged