DUOS-1274[risk=no] Refactored searchFilteredElectionList in Metrics Service for correct % SRP Approved cacl
broadinstitute/consent pull request #1090
Opened 2021-05-27 17:47 UTC by JVThomas

Addresses[DUOS-1274](https://broadworkbench.atlassian.net/browse/DUOS-1274)

PR corrects null check in searchFilteredElectionList and date references in associated MetricsDAO query.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-05-27 18:55 UTC, rushtong requested changes
I'm not confident this will solve the problem - have you run this code against staging? Let's get that set up for you if you haven't.

2021-05-27 18:55 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/db/MetricsDAO.java
> +      + "SELECT e.*, v.vote finalvote, v.rationale finalrationale, v.updatedate finalvotedate, MAX(e.electionid) "
Looking at `VoteDAO`, the only time we set a create date is on the update method. On dev, there are many more records with null update dates than create dates:
```
consent=> select count(voteid) from vote;
 count 
-------
 16971
(1 row)

consent=> select count(voteid) from vote where createdate is null;
 count 
-------
 14182
(1 row)

consent=> select count(voteid) from vote where updatedate is null;
 count 
-------
 16489
(1 row)
```

In ElectionDAO, we use the createDate for the final vote date exclusively so I don't think this is the correct approach.

2021-05-27 19:11 UTC, rushtong commented
Just to confirm, running this branch against the latest staging db shows the same incorrect info as noted in the ticket.

<img width="1730" alt="Screen Shot 2021-05-27 at 3 10 07 PM" src="https://user-images.githubusercontent.com/116679/119883644-c3728e00-befd-11eb-9d51-3423e29d22f3.png">

2021-05-27 19:22 UTC, rushtong approved these changes
This does show more accurate numbers. It also introduces room for improving the vote population code which is lacking.

2021-06-03 18:01 UTC, raejohanek approved these changes
I'm not exactly show how to test this out since it was an issue on staging, but the code looks good and when I check it out locally everything works well!

2021-06-03 18:02 UTC, rushtong approved these changes
Nice work!

2021-06-03 18:02 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/db/MetricsDAO.java
> +      + "END as finalvotedate, "
Very, very nice solution!

2021-06-04 13:36 UTC, merged