DUOS-1113[risk=no]We need a delete user role API
broadinstitute/consent pull request #1212
Opened 2021-08-05 17:13 UTC by raejohanek

SCOPE:
- Create service method that simply calls pre-existing DAO method
- Create new API, following structure of addRole API
- - Create helpers in UserRoles so that logic and code are not repeated in these two APIs
- - Create Tests
- - Add to api-docs

ADDRESSES:
- https://broadworkbench.atlassian.net/browse/DUOS-1113

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2021-08-06 19:11 UTC, JVThomas requested changes, later dismissed

2021-08-06 19:11 UTC, JVThomas commented on src/main/java/org/broadinstitute/consent/http/enumeration/UserRoles.java
> +        if (Objects.isNull(roleId) || roleId > 7 || roleId < 3) {
It's better to check for specific roles (could be a constant or an enum) rather than make general assumptions on id values. We don't know if future roles (if any) will follow the above trend.

2021-08-06 19:11 UTC, JVThomas commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                return Response.notModified().build();
304 relates to endpoints and caching, it's not used to describe an unchanged model or entity. Use a 404 with a message indicating the role was not found, which is safe to do here since it's an Admin only endpoint.

2021-08-06 19:15 UTC, raejohanek commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                return Response.notModified().build();
I am following the precedent set by the AddRole API which uses the not modified response. Do you think I should change them both then for consistency? It looks like the add role endpoint was written by greg about a year ago

2021-08-09 12:46 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                return Response.notModified().build();
Will look into this soon!

2021-08-09 12:47 UTC, rushtong commented
This is a Medium risk ticket since we're adding an API.

2021-08-10 16:44 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                return Response.notModified().build();
@raejohanek Justin is correct, we're using the 304 incorrectly in other places. Those should be updated to be a 200 response. Will file a ticket for that.

2021-08-10 17:06 UTC, rushtong requested changes
Looking good!

2021-08-10 17:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/enumeration/UserRoles.java
> +    }
This seems more like a `User` helper method than a `UserRoles` helper method.

2021-08-10 17:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/UserService.java
> +    }
Let's add some logging here, this is something we need to do more of. Let the method take a User as the user doing the action, and log (INFO) something like:
```
User 'Gregory Rushton' deleting Role Id: roleId from User ID: dacUserId
```

2021-08-10 17:06 UTC, rushtong commented on src/main/resources/assets/api-docs.yaml
> +            type: number
I understand that this is essentially the same as the add role API, but we can make this better in both places. This could be an enum with a selectable value from the UI. I think this will work, but haven't tested:
```
          schema:
            type: number
            nullable: false
            enum:
              - 3
              - 4
              - 5
              - 6
              - 7
```

2021-08-10 17:06 UTC, rushtong commented on src/main/resources/assets/api-docs.yaml
> +          description: Not modified, User does not have given role
rm

2021-08-10 17:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                return Response.notModified().build();
Added https://broadworkbench.atlassian.net/browse/DUOS-1393 to cover the add role endpoint.

2021-08-10 20:22 UTC, rushtong requested changes
Two minor suggestions, looking better!

2021-08-10 20:22 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/models/User.java
> +    }
This doesn't need the user ... it already is the user. 

```
    public List<Integer> getUserRoleIds() {
        if (Objects.isNull(this.getRoles())) {
            return Collections.emptyList();
        } else {
            return this.getRoles()
                    .stream()
                    .map(UserRole::getRoleId)
                    .collect(Collectors.toList());
        }
    }
```

2021-08-10 20:22 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/UserResource.java
> +                throw new BadRequestException("Role Id must be an Integer representing an allowed role (3 to 7)");
Let's simplify this message - we clearly spell out the requirements in Swagger.
```suggestion
                throw new BadRequestException("Invalid Role Id");
```

2021-08-11 14:16 UTC, rushtong commented
Still seeing [failed tests](https://github.com/DataBiosphere/consent/pull/1212/checks?check_run_id=3301661534), but they're passing for me locally.

2021-08-11 14:18 UTC, raejohanek commented
> Still seeing [failed tests](https://github.com/DataBiosphere/consent/pull/1212/checks?check_run_id=3301661534), but they're passing for me locally.

I was just going to say the same thing! I'm not sure why they pass locally and fail here, any ideas?

2021-08-11 19:20 UTC, rushtong approved these changes
Thank you for the changes!

2021-08-11 19:23 UTC, merged