[DUOS-1502][risk=no] Boosting health check test coverage
broadinstitute/consent pull request #1353
Opened 2021-11-12 20:44 UTC by MiriamAlter

- All new unit tests for Elastic Search health check
- New test for GCS health check exception case
- New tests for Ontology, Sam, & SendGrid health check configuration exception cases

Issue: https://broadworkbench.atlassian.net/browse/DUOS-1502

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2021-11-12 21:04 UTC, rushtong requested changes
Just a few minor suggestions for improvement, but overall, looks good! See comments inline.

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/ElasticSearchHealthCheckTest.java
> +    private RestClient client;
This is unused

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/ElasticSearchHealthCheckTest.java
> +        MockitoAnnotations.openMocks(this);
minor nit: `openMocks` could be a static import. We try to follow that pattern for the setup.

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/ElasticSearchHealthCheckTest.java
> +    }
This test should expect a failure case - it simplifies the code quite a bit
```suggestion
    @Test(expected = InternalServerErrorException.class)
    public void testCheckServerFailure() throws Exception {
        initHealthCheck("green", HttpStatusCodes.STATUS_CODE_SERVER_ERROR);
        healthCheck.check();
    }
```

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/GCSHealthCheckTest.java
> +        assertTrue(result.getMessage().contains("GCS bucket unreachable"));
nit: I generally don't like to test error messages - it doesn't really add anything to the test nor does it test any real logic. The basic health condition is the primary concern here. There are exceptions to this rule, but I don't think this is one of them.

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/OntologyHealthCheckTest.java
>      MockitoAnnotations.openMocks(this);
Looks like this is a case where we didn't import the static in the original code, but we should.

2021-11-12 21:04 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/health/SamHealthCheckTest.java
>      MockitoAnnotations.openMocks(this);
Same here ... and this is relatively recent code. Shame on me.

2021-11-12 21:18 UTC, MiriamAlter commented on src/test/java/org/broadinstitute/consent/http/health/ElasticSearchHealthCheckTest.java
> +    }
I used the syntax I learned in SG, but thanks for showing me a better one.

2021-11-12 21:20 UTC, MiriamAlter commented on src/test/java/org/broadinstitute/consent/http/health/GCSHealthCheckTest.java
> +        assertTrue(result.getMessage().contains("GCS bucket unreachable"));
The other tests included messages as well. I thought it made the most sense to continue the pattern.

2021-11-15 10:25 UTC, rushtong approved these changes
Thank you for the changes 👍🏽

2021-11-15 14:30 UTC, merged