[DUOS-1762][risk=no] Back-populate join table
broadinstitute/consent pull request #1618
Opened 2022-06-28 20:39 UTC by phendriksen100

----
### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-1762

- Back populates the dar_dataset table
- Deprecates getDatasetIds, setDatasetIds, datasetIds

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-06-29 15:48 UTC, quazi-broad reviewed
Changes here look good to me. SQL query is pulling unique dataset_id and reference_id combos from all DARs and inserting them to the join table. I think you may need to add this changelog (84.0) to the changelog-master.xml for it to get picked up as it was not being applied when I spun the docker up locally.

I haven't made any changelog files yet but I was wondering if we needed semicolons at the end of sql statements? Looking at older changelog files, some of them do have semicolons while others do not - it is not consistent.

2022-06-29 17:10 UTC, rushtong commented on src/main/resources/changesets/changelog-consent-84.0.xml
> +    <changeSet id="83.0" author="phendriksen">
The ID should be 84:
```suggestion
    <changeSet id="84.0" author="phendriksen">
```

2022-06-29 17:11 UTC, rushtong requested changes
One minor detail, then 👍🏽

2022-06-29 19:26 UTC, phendriksen100 commented on src/main/resources/changesets/changelog-consent-84.0.xml
> +    <changeSet id="83.0" author="phendriksen">
ahhhhhhh. Thank you!

2022-06-29 20:41 UTC, quazi-broad approved these changes
Looks good 👍🏽

2022-06-30 10:13 UTC, rushtong approved these changes
👍🏽

2022-06-30 15:29 UTC, merged