[DUOS-1976][risk=no] deprecate endpoints for DulReview, DulPreview, DulCollection, DulResultRecords
broadinstitute/consent pull request #1683
Opened 2022-08-02 19:16 UTC by shaemarks

Addresses [DUOS-1976](https://broadworkbench.atlassian.net/browse/DUOS-1976)

I wasn't able to find swagger documentation for `GET /api/election/vote/${voteId}` or the actual resource method for `GET /api/consent/${consentId}/dul`

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-08-04 15:42 UTC, connorlbark requested changes

2022-08-04 15:42 UTC, connorlbark commented on src/main/resources/assets/api-docs.yaml
> +      deprecated: true
I believe this endpoint (at ElectionReviewResource.java:59) does not have an `@Deprecated` tag.

2022-08-04 16:37 UTC, rushtong commented
> I wasn't able to find ... the actual resource method for `GET /api/consent/${consentId}/dul`

Hah - it looks like I deleted it [here](https://github.com/DataBiosphere/consent/pull/910/files#diff-44109c1a51fe73bf0340a5dad2a9951d6c12f0bfac4024c2145acd8e7cf0f84fL142), sorry about that.

2022-08-04 16:38 UTC, rushtong approved these changes
+1 to Connor's feedback, otherwise, 👍🏽. Please feel free to merge after that fix.

2022-08-04 16:45 UTC, shaemarks commented on src/main/resources/assets/api-docs.yaml
> +      deprecated: true
Thanks for catching this!

2022-08-08 14:54 UTC, connorlbark approved these changes

2022-08-08 15:01 UTC, merged