[DUOS-2055][risk=no] Add ITDirector role
broadinstitute/consent pull request #1750
Opened 2022-09-16 18:56 UTC by connorlbark

## Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2055

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2022-09-20 19:13 UTC, quazi-broad approved these changes
Changes look good and are working correctly. I see IT Director listed under the two main role endpoints. I am able to add the ITDirector role to a user as well as delete the role using those existing PUT/DELETE endpoints.

I'm not sure if it's in the scope of this ticket, but do we need to update the DarCollection endpoints that use {roleName} as a parameter? Most of them are GET endpoints that filter by role:
DarCollectionResource
	getCollectionsForUserByRole
	getCollectionSummariesForUserByRole
	getCollectionSummaryForRoleById
	queryCollectionsByFiltersAndUserRoles
	getCollectionsByToken	
IT Director is not available in the drop down menus for selecting a role for those endpoints.

Also, I was trying to test the updateSelf and update endpoints under UserResource and was able to remove a ITDirector role but have been unable to add one but I think I'm just doing it incorrectly.

2022-09-21 11:59 UTC, JVThomas commented
The ticket states the following
`Update Roles, and the various PUT role apis that follows the same restrictions as Signing Official. In future stories, we will restrict an IT Director user from modifying their institution in the UI, similarly to what we do for SOs.`

In the case of an SO or IT Director, user's should not be able to update their own institutions once the role has been assigned to them. In previous endpoints this was enforced, however it seems that the current `updateSelf` endpoint does not, so this functionality needs to be added back in.

The ticket also introduces a new functionality to the user update flow. Previously only Admins were allowed to add and remove roles, but now we're extending it to SO's, but in a very limited sense. SO's should now be able to add or remove the SO role for any user within their current institution.

Regarding this line...
`SOs can access this API to add remove other SO and IT Director roles from their institution. On add, we add the SO’s institution to the user`

This line basically means that SOs can assign SO and IT Director roles to users that DO NOT have an institution assigned. This allows SOs to be proactive and bring in newly registered SOs and IT directors into their institution by simply assigning roles.

In the case of removing the roles, you do not need to remove the institution, just the role. This will allow us to accommodate a scenario where a user has the role removed but is still in the institution as well as a scenario where the user has left the institution.

This is a lot, which is why I recommend splitting the tasks into separate tickets. This PR should add the role and ensure that users cannot change their own institutions if they are an IT Director or SO. The rest of the functionality should be tackled in a different ticket.

You've done the role addition portion, so all that's left is the institution update checks for IT Director and SO (since that should've been present to begin with).

2022-09-26 18:41 UTC, connorlbark commented
ok!! so i changed the update self endpoint to only let you change your institution id if it's not set already if you're an SO or an ITD

2022-09-28 12:01 UTC, JVThomas requested changes
Functionally the code is there, there's just some hiccups with the changelog and database that needs to be addressed.

2022-09-28 12:01 UTC, JVThomas commented on src/main/resources/changesets/changelog-consent-100.0.xml
> +  <changeSet id="99.0" author="connorlbark">
Update the id to 100.0 and add the file to the changelog-master

2022-09-28 12:01 UTC, JVThomas commented on src/main/resources/changesets/changelog-consent-100.0.xml
> +          <column name="roleid" value="9"/>
Normally you shouldn't have to include the `roleid` on an insert since it's supposed to be an auto-incrementing value. However I see that there have been earlier changelog files that manually added the id for older roles, and as a result the auto-increment never updated properly (its at 7 when it should be at 9).

We can fix this behavior by using an sql script to reset the auto-increment value to 9. So right before the insert tag, add this...

```
<sql>
    ALTER SEQUENCE roles_roleid_seq RESTART WITH 9
</sql>
 ```
 
This will reset the auto-increment tag to 9. Then, in your insert tag, remove the id assignment and the auto-increment should work as expected.
 
 NOTE: Generally the auto-increment value is saved internally in PostgreSQL in the form `{tablename}_{incrementing column name}_seq`, but you can always see for yourself in Postico by looking at the Structure tab of a table and looking at the `Sequence` column.
 
<img width="1787" alt="Screen Shot 2022-09-28 at 7 48 14 AM" src="https://user-images.githubusercontent.com/6664778/192771527-a2d37589-7ff1-49d4-9b1f-7244efa9f2e8.png">

2022-09-28 14:23 UTC, connorlbark commented on src/main/resources/changesets/changelog-consent-100.0.xml
> +          <column name="roleid" value="9"/>
ahhhhh, this is a very good catch, much much cleaner this way. thanks!!

2022-09-28 14:24 UTC, connorlbark commented
I also added a test which makes sure all roles in UserRoles can be added to a user (making sure that each role actually exists in the Roles db). This way, there's some way to catch that even if the role isn't added in any other tests.

2022-09-28 15:50 UTC, JVThomas commented
> I also added a test which makes sure all roles in UserRoles can be added to a user (making sure that each role actually exists in the Roles db). This way, there's some way to catch that even if the role isn't added in any other tests.

Good thinking. It's a simple test that ensures that the roles saved in the database line up with the roles declared in the `UserRoles` enum

2022-09-28 17:42 UTC, JVThomas approved these changes
Code looks good to me, though I suggest getting a re-view from @quazi-broad or anyone else for an updated second thumb

2022-09-29 17:58 UTC, quazi-broad approved these changes
New changes and tests look good to me!

2022-09-30 14:39 UTC, merged