[DUOS-2473] Elasticsearch dataset query
broadinstitute/consent pull request #2103
Opened 2023-07-18 17:26 UTC by fboulnois

### Addresses

https://broadworkbench.atlassian.net/browse/DUOS-2473

### Summary

Code to query the elasticsearch endpoint.

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2023-07-24 13:00 UTC, kaitlynoflaherty approved these changes
Looks good

2023-07-24 13:37 UTC, rushtong requested changes
Have not been able to get this to function yet - need to debug the parsing error some more. I think we could also use some example(s) and expanded description in the swagger docs to make it easier for UI devs to make use of this endpoint.

2023-07-24 13:37 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/ElasticSearchService.java
> +  public boolean validateQuery(String query) throws IOException {
This is nice, thank you!

2023-07-24 13:37 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DatasetResource.java
>    public Response searchDatasetIndex(@Auth AuthUser authUser, String query) {
I think we need a `@PermitAll` line for this method - I definitely missed this in my earlier review.

2023-07-24 13:37 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/ElasticSearchService.java
> +    return esClient.performRequest(searchRequest);
I'm seeing a `JerseyGsonProvider` exception parsing the response for what should be a valid query
```
{ "query": { "query_string": { "query": "(GRU) OR (HMB)" } } }
```
...
```
consent  | ERROR [2023-07-24 13:28:17,461] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 9db3ef52a2d8eada
consent  | ! java.lang.reflect.InaccessibleObjectException: Unable to make field final byte[] java.nio.ByteBuffer.hb accessible: module java.base does not "opens java.nio" to unnamed module @3b4ce44c
consent  | ! at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
consent  | ! at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
consent  | ! at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
consent  | ! at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
consent  | ! at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
consent  | ! ... 84 common frames omitted
```

2023-07-25 19:55 UTC, rushtong commented on src/main/resources/assets/schemas/DatasetSearch.yaml
> +properties:
There should be a lot more potential properties here (see [DatasetSearchTerm](https://github.com/DataBiosphere/consent/blob/develop/src/main/java/org/broadinstitute/consent/http/models/DatasetSearchTerm.java)). I think we still have a bug where a lot of those fields are not actually being sent to ES right now.

2023-07-25 20:17 UTC, rushtong approved these changes
Looks and works great! We can likely use some additional documentation somewhere for UI dev. I was able to see valid results for a variety of queries, very exciting!
```
{ "query": { "match": { "dataUse.primary.code": "DS"} } }

{ "query": { "match": { "dataUse.secondary.code": "NCU"} } }

{ "query": { "match": { "approvedUserIds": 4949} } }

{
  "query": {
    "bool": {
      "must": [
        { "match": { "approvedUserIds": 4949} },
        { "match": { "dataUse.primary.code": "GRU"} }
      ]
    }
  }
}
```

2023-07-25 20:19 UTC, rushtong commented
Approval caveat ... let's get the tests to pass.

2023-07-26 18:42 UTC, rushtong approved these changes
Thank you for the changes 👍🏽

2023-07-26 21:04 UTC, merged