[DUOS-2709][risk=no] Delete Dataset Updates
broadinstitute/consent pull request #2171
Opened 2023-10-25 20:30 UTC by rushtong

### Addresses
https://broadworkbench.atlassian.net/browse/DUOS-2709

### Summary
Minor refactor for deleting a dataset
* Ensure dataset is deletable before trying to delete it
* Move deletion code to DAO
* Ensure dataset is removed from index

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2023-10-27 14:28 UTC, fboulnois requested changes
One recommendation:

2023-10-27 14:28 UTC, fboulnois commented on src/test/java/org/broadinstitute/consent/http/service/dao/DatasetServiceDAOTest.java
> +//    doNothing().when(datasetDAO).deleteConsentAssociationsByDatasetId(any());
nit: remove or update these checks?

2023-10-27 15:21 UTC, rushtong commented on src/test/java/org/broadinstitute/consent/http/service/dao/DatasetServiceDAOTest.java
> +//    doNothing().when(datasetDAO).deleteConsentAssociationsByDatasetId(any());
Yes, thank you!

2023-10-27 17:15 UTC, fboulnois approved these changes
lgtm 👍

2023-10-30 13:39 UTC, hams7504 approved these changes
👍

2023-10-30 14:55 UTC, merged