BTRX-435 /  BTRX-436 / BTRX-417 Download DAA & Upload DAA
broadinstitute/consent pull request #314
Opened 2018-11-26 19:37 UTC by vvicario

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/DataBiosphere/consent/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing
- [ ] I've updated Swagger to reflect any API changes

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-11-26 23:06 UTC, rushtong requested changes
Some minor nits and suggestions, but looks good!

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/cloudstore/GCSStore.java
> +            logger().error("Error deleting document.", e);
Nit: It would be nice to have more information in the logs for debugging. The url would be helpful too.

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessAgreementResource.java
> +import javax.ws.rs.*;
Nit: avoid *-imports. See https://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports for getting your IDE to do this for you.

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessAgreementResource.java
> +        catch (Exception e) {
nit: catch should be on same line as preceding `}`

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessRequestResource.java
> +                logger.log(Level.SEVERE, "while creating useRestriction " + dar.toJson(), e);
nit: Error message could use some help
```suggestion
                logger.log(Level.SEVERE, "Error creating use restriction for data access request " + dar.toJson(), e);
```

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessRequestResource.java
> +            store.deleteStorageDocument(dar.getString(ResearcherFields.URL_DAA.getValue()));
Shouldn't we log this exception here?

2018-11-26 23:06 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/service/DatabaseDataAccessRequestAPI.java
> +         return rpList;
nit: extra space, please revert

2018-11-27 19:38 UTC, vvicario commented
@rushtong I worked on your feedback!

2018-11-27 20:17 UTC, LeoForconesi reviewed
:+1:

2018-11-27 20:26 UTC, rushtong approved these changes
👍

2018-11-27 20:33 UTC, merged

2019-09-17 12:15 UTC, rushtong commented on src/main/java/org/broadinstitute/consent/http/resources/DataAccessAgreementResource.java
> +                FileUtils.copyInputStreamToFile(r.getContent(), targetFile);
I missed this in review. This creates a file in root that is never cleaned up. Filed https://broadinstitute.atlassian.net/browse/DUOS-452 for this.